spring.application.name=PracticeProject
spring.datasource.url=jdbc:mysql://localhost:3306/userinformation
spring.datasource.username=root
spring.datasource.password=Raju@6165

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging.level.org.hibernate.SQL = DEGUB
Logging.level.org.hibernate.orm.idbc.bind = TRACE
Logging.level.com.springboot.PracticeProject = debug

jwt.secret = JWT_SECRET
jwt.issuer = CodeKaro
jwt.expiry = 180000
jwt.expiration-days = 7

file.upload-dir = uploads